apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: 'https://github.com/stianfro/minecraft-gitops.git'
    path: charts/minecraft
    helm:
      values: |-
        minecraft:
          gamemode: survival
          motd: 'minecraft.froystein.jp'
          port: 25565
        volume:
          storageClass: hostpath

  destination:
    server: 'https://kubernetes.default.svc'
