minecraft:
  gamemode: 'survival'
  motd: 'minecraft.froystein.jp'
  port: 25565

volume:
  storage: 3Gi

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi

serviceAccount:
  create: true